import requests

DEFAULT_GROWW_TICKERS = [
    "APTUS", "AAVAS", "KAYNES", "ANANTRAJ", "ITC", "ITCHOTELS", "MANKIND",
    "RELIANCE", "JIOFIN", "BAJAJHFL", "BAJFINANCE", "TCS", "HCLTECH", "TECHM", "WIPRO",
    "SAGILITY", "DLF", "SOBHA", "MOREALTY", "DIXON", "LICI", "HDFCLIFE", "SBIN", "HDFCBANK",
    "BANKBEES", "NIFTYBEES", "ITBEES", "HDFCSML250", "MIDCAPETF", "MODEFENCE",
    "FMCGIETF", "GROWWPOWER", "GOLDBEES", "SILVERBEES", "INFY", "ICICIBANK", 
    "AXISBANK", "KOTAKBANK", "LT", "HINDUNILVR", "BHARTIARTL", "TATAMOTORS", 
    "SBILIFE", "TATASTEEL", "ADANIENT", "ASIANPAINT", "MARUTI", "SUNPHARMA", 
    "NTPC", "POWERGRID", "TITAN", "COALINDIA", "BAJAJFINSV", "BPCL", "ONGC", 
    "JSWSTEEL", "HINDALCO", "GRASIM", "EICHERMOT", "JINDALSTEL", "HAL", "BEL", 
    "ZOMATO", "TRENT", "MUTHOOTFIN", "RECLTD", "PFC", "BHEL", "RVNL", "IRFC", 
    "MAZDOCK", "SUZLON"
]

NIFTY_50 = DEFAULT_GROWW_TICKERS

NIFTY_NEXT_50 = [
    "ABB", "ACC", "AMBUJACEM", "APOLLOHOSP", "DMART", "BAJAJHLDNG", "BANKBARODA", "BERGERPAINT",
    "BEL", "BOSCHLTD", "CANBK", "CHOLAFIN", "COLPAL", "CONCOR", "DLF", "DABUR", "GAIL", "GICRE",
    "GODREJCP", "HAL", "HAVELLS", "HEROMOTOCO", "ICICILI", "IOC", "IRCTC", "IRFC", "JINDALSTEL", "JIOFIN",
    "LICHSGFIN", "LTIM", "MARICO", "MUTHOOTFIN", "NTPC", "PIIND", "PIDILITIND", "PFC", "PNB", "RECLTD",
    "SBICARD", "SRF", "SHREECEM", "SHRIRAMFIN", "SIEMENS", "TVSMOTOR", "TATAPOWER", "TATACOMM", "TRENT", "VEDL"
]

NIFTY_MIDCAP_150 = [
    "PFC", "RECLTD", "TVSMOTOR", "LUPIN", "MRF", "AUROPHARMA", "ASHOKLEY", "IDFCFIRSTB", "ASTRAL", "CUMMINSIND",
    "VOLTAS", "OBEROIRLTY", "JUBLFOOD", "IDEA", "BIOCON", "BANDHANBNK", "ZEEL", "PAYTM", "ZOMATO", "NYKAA",
    "POLICYBZR", "MOTHERSON", "BHEL", "SAIL", "CONCOR", "ABCAPITAL", "ESCORTS", "COROMANDEL", "MFSL", "DALBHARAT"
]

NIFTY_SMALLCAP_250 = [
    "SUZLON", "IRFC", "RVNL", "MAZDOCK", "KALYANKJIL", "ANGELONE", "CDSL", "BSE", "MCX", "RADICO",
    "CEATLTD", "BLS", "LATENTVIEW", "CYIENT", "ZENSARTECH", "SONACOMS", "CAMS", "HAPPSTMNDS", "GLENMARK", "JBCHEPHARM",
    "GRANULES", "NATCOPHARM", "UCOBANK", "CENTRALBK", "IOB", "MAHABANK", "J&KBANK", "CSBBANK", "KARURVYSYA", "SOUTHBANK"
]

NIFTY_500 = list(set(NIFTY_50 + NIFTY_MIDCAP_150 + NIFTY_SMALLCAP_250))

# Major Indices for Scan Universe
NIFTY_BANK = [
    "HDFCBANK", "ICICIBANK", "KOTAKBANK", "SBIN", "AXISBANK", "INDUSINDBK", "BANDHANBNK", "IDFCFIRSTB",
    "FEDERALBANK", "YESBANK", "AUBANK", "BANKBARODA", "PNB", "UNIONBANK", "CANBK", "IOB"
]

NIFTY_IT = [
    "TCS", "INFY", "WIPRO", "HCLTECH", "TECHM", "OFFICEY", "CIPLA", "SUNPHARMA", "DRREDDY", "APOLLOPH",
    "DIVISLAB", "BIOCON", "LUPIN", "TORNTPHARM", "ZYDUSLIFE", "ALKEM", "AUROPHARMA", "GSKCONS",
    "ABBOTINDIA", "PFIZER"
]

NIFTY_FINANCIAL = [
    "BAJFINANCE", "HDFCBANK", "HDFCLIFE", "SBICARD", "BAJAJFINSV", "ICICIPRULI", "SBILIFE", "MUTHOOTFIN",
    "CHOLAFIN", "LICHSGFIN", "MANAPPURAM", "POONAWALLA", "JIOFIN", "EQUITASBNK", "AUTOAXLES",
    "KARURVYSYA", "PFC", "RECLTD", "IRFC", "SHRIRAMFIN",
]

NIFYAUTO = [
    "MARUTI", "TATAMOTORS", "M&M", "BOSCH", "HEROMOTOCO", "BAJAJ-AUTO", "EICHERMOT", "TVSMOTOR",
    "FORCEMOT", "TATACONSUM", "AMARAJABAT", "EXIDEIND", "AMBER", "TIINDIA", "MOTALAM", "WABCOINDIA",
    "SUZLON", "NILKAMAL", "MRF", "APOLLOTYRE", "JKTYRE"
]

NIFTY_FMCG = [
    "HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA", "DABUR", "MARICO", "GODREJCP",
    "RADICO", "TATACONSUM", "VBL", "JUBLFOOD", "BPL", "PGHH",
    "COLPAL", "DODLA", "KAJARIACER", "GOLDBEES", "HONAUT"
]

NIFTY_METAL = [
    "TATASTEEL", "JSWSTEEL", "HINDALCO", "VEDANTA", "SAIL", "NMDC", "COALINDIA", "RATNAMANI",
    "JINDALSTEL", "WELCORP", "TINPLATE", "JSL", "JSLHISAR", "KIRLFER", "GRAUWE", "MOIL",
    "CENTURYTTX", "ROLTA", "SYNTHW", "ASHIANA"
]

NIFTY_REALTY = [
    "DLF", "SOBHA", "PRESTIGE", "GODREJPROP", "OBEROIRLTY", "BRIGADE", "MAHINDIA", "TATAELXSI",
    "LODHA", "SUNTECK", "INDOCO", "FORWORK", "NOBLE", "ASHIANA", "A1FLORR", "ARSHIYA",
    "MAXESTATES", "PATIN", "SHRIRAMP", "VIVIDHA"
]

NIFTY_ENERGY = [
    "RELIANCE", "ONGC", "IOC", "BPCL", "HPCL", "GAIL", "ADANIGREEN", "ADANIENT",
    "ADANIPOWER", "TATAPOWER", "NTPC", "POWERGRID", "JSWENERGY", "NHPC", "SJVN", "TORNTPOWER",
    "NLCINDIA", "CESC", "GGCL", "RPOWER"
]

from app.market_pulse.nifty_index_constituents import (
    NIFTY_CEMENT,
    NIFTY_CHEMICALS,
    NIFTY_CONSUMER_DURABLES,
    NIFTY_FINANCIAL_SERVICES_EX_BANK,
    NIFTY_HEALTHCARE,
)

NIFTY_MIDCAP = NIFTY_MIDCAP_150

# ---------------------------------------------------------------------------
# US markets — full index lists via us_index_constituents (lazy-loaded)
# ---------------------------------------------------------------------------

from app.market_pulse.us_index_constituents import (  # noqa: E402
    DOW_30_STATIC as DOW_30,
    US_INDEX_ETFS,
    get_us_index_options,
)

INDEX_OPTIONS = {
    "Default Groww Tickers": DEFAULT_GROWW_TICKERS,
    "NIFTY 50": NIFTY_50,
    "NIFTY NEXT 50": NIFTY_NEXT_50,
    "NIFTY BANK": NIFTY_BANK,
    "NIFTY IT": NIFTY_IT,
    "NIFTY FINANCIAL SERVICES": NIFTY_FINANCIAL,
    "NIFTY AUTO": NIFYAUTO,
    "NIFTY FMCG": NIFTY_FMCG,
    "NIFTY METAL": NIFTY_METAL,
    "NIFTY REALTY": NIFTY_REALTY,
    "NIFTY ENERGY": NIFTY_ENERGY,
    "NIFTY CEMENT": NIFTY_CEMENT,
    "NIFTY CHEMICALS": NIFTY_CHEMICALS,
    "NIFTY CONSUMER DURABLES": NIFTY_CONSUMER_DURABLES,
    "NIFTY HEALTHCARE": NIFTY_HEALTHCARE,
    "NIFTY FINANCIAL SERVICES EX-BANK": NIFTY_FINANCIAL_SERVICES_EX_BANK,
    "NIFTY MIDCAP 150": NIFTY_MIDCAP,
    "NIFTY SMALLCAP 250": NIFTY_SMALLCAP_250,
    "NIFTY 500": NIFTY_500
}

# Market labels (shared across tabs)
GROWW_MARKET = "Groww (India Stocks)"
US_MARKET = "US Stocks (Yahoo)"
CRYPTO_MARKET = "CoinDCX Futures"
MARKET_OPTIONS = [GROWW_MARKET, US_MARKET, CRYPTO_MARKET]


def is_crypto_market(market: str) -> bool:
    return "CoinDCX" in (market or "")


def is_us_market(market: str) -> bool:
    m = (market or "").strip()
    return m == US_MARKET or "US Stocks" in m


def is_india_market(market: str) -> bool:
    return not is_crypto_market(market) and not is_us_market(market)


def market_currency(market: str) -> str:
    if is_india_market(market):
        return "₹"
    return "$"


def get_index_options_for_market(market: str) -> dict[str, list[str]]:
    if is_us_market(market):
        return get_us_index_options()
    return INDEX_OPTIONS


COINDCX_USDT_TICKERS = [
    "B-BTCUSDT", "B-ETHUSDT", "B-SOLUSDT", "B-XRPUSDT", "B-DOGEUSDT", 
    "B-ADAUSDT", "B-AVAXUSDT", "B-LINKUSDT", "B-DOTUSDT", "B-NEARUSDT", 
    "B-LTCUSDT", "B-SHIBUSDT", "B-PEPEUSDT", "B-WIFUSDT", "B-BONKUSDT", 
    "B-JUPUSDT", "B-ONDOUSDT", "B-OMUSDT", "B-FLOKIUSDT", "B-SUIUSDT", 
    "B-RENDERUSDT", "B-TAOUSDT", "B-FETUSDT", "B-ARUSDT", "B-TIAUSDT", 
    "B-SEIUSDT", "B-STRKUSDT", "B-OPUSDT", "B-ARBUSDT", "B-LDOUSDT", 
    "B-UNIUSDT", "B-ICPUSDT", "B-ALGOUSDT", "B-VETUSDT", "B-XLMUSDT", 
    "B-ATOMUSDT", "B-GRTUSDT", "B-IMXUSDT", "B-RUNEUSDT", "B-THETAUSDT", 
    "B-INJUSDT", "B-STXUSDT", "B-AAVEUSDT", "B-MKRUSDT", "B-GMTUSDT", 
    "B-GALAUSDT", "B-ZILUSDT", "B-KAVAUSDT", "B-JASMYUSDT", "B-WLDUSDT", 
    "B-CRVUSDT", "B-1INCHUSDT", "B-MINAUSDT", "B-ENJUSDT", "B-FLOWUSDT", 
    "B-MANAUSDT", "B-SANDUSDT", "B-AXSUSDT", "B-DYDXUSDT", "B-BATUSDT", 
    "B-WOOUSDT", "B-KSMUSDT", "B-QTUMUSDT", "B-ZRXUSDT", "B-ONEUSDT", 
    "B-HOTUSDT", "B-CELOUSDT", "B-RVNUSDT", "B-ROSEUSDT", "B-IOTXUSDT", 
    "B-EGLDUSDT", "B-RSRUSDT", "B-STGUSDT", "B-SPELLUSDT", "B-LUNA2USDT", 
    "B-SFPUSDT", "B-COMPUSDT", "B-YFIUSDT", "B-SNXUSDT", "B-POLUSDT",
    "B-SAGAUSDT", "B-SPXUSDT", "B-BASEDUSDT", "B-SAPIENUSDT", "B-FHEUSDT", "B-ATAUSDT",
    "B-MERLUSDT", "B-STABLEUSDT", "B-2ZUSDT", "B-FIGHTUSDT", "B-GTCUSDT",
    "B-REZUSDT", "B-SYSUSDT", "B-PRLUSDT", "B-MITOUSDT", "B-HUSDT", "B-EIGENUSDT",
    "B-NFPUSDT", "B-BERAUSDT", "B-CHILLGUYUSDT", "B-CATIUSDT", "B-OPNUSDT", "B-CETUSUSDT", "B-WUSDT",
    "B-PYTHUSDT", "B-EULUSDT", "B-AIGENSYNUSDT", "B-MAVIAUSDT", "B-SWARMSUSDT", "B-KMNOUSDT", "B-LUMIAUSDT",
    "B-ATHUSDT", "B-ACEUSDT", "B-MEWUSDT", "B-XAGUSDT", "B-AKTUSDT", "B-XPLUSDT", "B-WALUSDT",
    "B-DOLOUSDT", "B-ACTUSDT", "B-FARTCOINUSDT", "B-INITUSDT", "B-BBUSDT",
    "B-PLUMEUSDT", "B-1000000MOGUSDT", "B-PHAUSDT", "B-BANANAS31USDT", "B-MOVRUSDT", "B-FOGOUSDT",
    "B-IOUSDT", "B-ALTUSDT", "B-EDUUSDT", "B-MOCAUSDT", "B-SIGNUSDT", "B-0GUSDT",
    "B-ZKUSDT", "B-AGLDUSDT", "B-SOLVUSDT", "B-CUSDT", "B-MBOXUSDT", "B-BLURUSDT",
    "B-MANTAUSDT", "B-ZROUSDT", "B-XAIUSDT", "B-LISTAUSDT", "B-TURTLEUSDT", "B-EDGEUSDT",
    "B-TREEUSDT", "B-IOTAUSDT", "B-BRETTUSDT", "B-SCRTUSDT", "B-DYMUSDT", "B-MANTRAUSDT", "B-COTIUSDT",
    "B-EPICUSDT", "B-FIDAUSDT", "B-ETHFIUSDT", "B-NXPCUSDT", "B-CARVUSDT", "B-SCRUSDT", "B-YGGUSDT",
    "B-SHELLUSDT", "B-RPLUSDT", "B-BMTUSDT", "B-JOEUSDT", "B-USUALUSDT", "B-EDENUSDT", "B-C98USDT", "B-HEMIUSDT",
    "B-HFTUSDT", "B-CFXUSDT", "B-TNSRUSDT", "B-HAEDALUSDT", "B-PIXELUSDT", "B-MOODENGUSDT", "B-LQTYUSDT",
    "B-VANRYUSDT", "B-SKLUSDT", "B-ONGUSDT", "B-SXTUSDT", "B-MEMEUSDT", "B-MMTUSDT", "B-TRUMPUSDT",
    "B-DIAUSDT", "B-IDUSDT", "B-BICOUSDT", "B-ENSUSDT", "B-MORPHOUSDT", "B-TONUSDT", "B-BIGTIMEUSDT",
    "B-IOSTUSDT", "B-LAUSDT", "B-DRIFTUSDT", "B-MAVUSDT", "B-ICNTUSDT", "B-DEEPUSDT",
    "B-ORDIUSDT", "B-GOATUSDT", "B-PORTALUSDT", "B-AVAUSDT", "B-IPUSDT",
    "B-MAGICUSDT", "B-AUSDT", "B-ARKMUSDT", "B-CHRUSDT", "B-FLUIDUSDT", "B-CFGUSDT", "B-NILUSDT", "B-ZKCUSDT",
    "B-SSVUSDT", "B-FRAXUSDT", "B-MIRAUSDT", "B-BREVUSDT", "B-AVNTUSDT", "B-ILVUSDT",
    "B-MASKUSDT", "B-SOMIUSDT", "B-BIOUSDT", "B-THEUSDT", "B-NEWTUSDT", "B-BANDUSDT",
    "B-WCTUSDT", "B-SYNUSDT", "B-APEUSDT", "B-PEOPLEUSDT", "B-ERAUSDT", "B-GRASSUSDT",
    "B-ZETAUSDT", "B-API3USDT", "B-FLUXUSDT", "B-SONICUSDT", "B-1000SATSUSDT",
    "B-METISUSDT", "B-KASUSDT", "B-LINEAUSDT", "B-YBUSDT", "B-HIGHUSDT", "B-HMSTRUSDT",
    "B-WETUSDT", "B-POPCATUSDT", "B-HEIUSDT", "B-TLMUSDT", "B-ONTUSDT",
    "B-NOTUSDT", "B-SUSHIUSDT", "B-MOVEUSDT", "B-RLCUSDT", "B-SUSDT", "B-USTCUSDT", "B-BOMEUSDT",
    "B-STOUSDT", "B-KOMAUSDT", "B-CYBERUSDT", "B-1000CATUSDT", "B-BROCCOLI714USDT", "B-GUSDT", "B-RAREUSDT",
    "B-RAVEUSDT", "B-KATUSDT", "B-MEGAUSDT", "B-METUSDT", "B-RONINUSDT",
    "B-RESOLVUSDT", "B-SKRUSDT", "B-PROVEUSDT", "B-ETHWUSDT", "B-ZENUSDT",
    "B-SYRUPUSDT", "B-TOWNSUSDT", "B-AXLUSDT", "B-ALICEUSDT", "B-LSKUSDT", "B-TACUSDT", "B-BSVUSDT", "B-MEUSDT", "B-ALPINEUSDT", "B-VELODROMEUSDT",
    "B-AVAAIUSDT", "B-CTSIUSDT", "B-ANIMEUSDT", "B-VTHOUSDT", "B-ROBOUSDT",
    "B-SAFEUSDT", "B-ARKUSDT", "B-SOPHUSDT", "B-ICXUSDT", "B-NEOUSDT", "B-SUPERUSDT", "B-COWUSDT", "B-MONUSDT", "B-SENTUSDT", "B-AEROUSDT", "B-GASUSDT", "B-ACUUSDT",
    "B-PUMPUSDT", "B-SAHARAUSDT", "B-BANANAUSDT", "B-HIVEUSDT", "B-VVVUSDT", "B-OGNUSDT",
    "B-LPTUSDT", "B-FUSDT", "B-MUBARAKUSDT", "B-NOMUSDT", "B-TAIKOUSDT",
    "B-GENIUSUSDT", "B-MELANIAUSDT", "B-PNUTUSDT", "B-PUNDIXUSDT", "B-UMAUSDT",
    "B-DOGSUSDT", "B-ALLOUSDT", "B-REDUSDT", "B-LAYERUSDT", "B-COOKIEUSDT", "B-1MBABYDOGEUSDT",
    "B-TUSDT", "B-GIGGLEUSDT", "B-PIPPINUSDT", "B-XMRUSDT", "B-BELUSDT", "B-WLFIUSDT",
    "B-KITEUSDT", "B-WAXPUSDT", "B-FORMUSDT", "B-XTZUSDT", "B-CHIPUSDT", "B-LITUSDT", "B-XVSUSDT", "B-PENGUUSDT",
    "B-BARDUSDT", "B-ACHUSDT", "B-ZKPUSDT", "B-TWTUSDT", "B-TUTUSDT", "B-HOLOUSDT", "B-BNTUSDT",
    "B-BANKUSDT", "B-KAITOUSDT", "B-KAIAUSDT", "B-SANTOSUSDT", "B-BIRBUSDT",
    "B-HUMAUSDT", "B-HYPERUSDT", "B-GRIFFAINUSDT", "B-MTLUSDT", "B-PHBUSDT", "B-GLMUSDT", "B-VANAUSDT",
    "B-AIXBTUSDT", "B-CLANKERUSDT", "B-HBARUSDT", "B-CAKEUSDT", "B-XANUSDT"
]


def get_coindcx_ticker_list():
    return [{"symbol": t, "display": t.replace("B-", "").replace("USDT", "-USDT")} for t in COINDCX_USDT_TICKERS]
