"""India/US/crypto index and ticker universes for Market Pulse."""

from __future__ import annotations

DEFAULT_GROWW_TICKERS = [
    "APTUS", "AAVAS", "KAYNES", "ANANTRAJ", "ITC", "ITCHOTELS", "MANKIND",
    "RELIANCE", "JIOFIN", "BAJAJHFL", "BAJFINANCE", "TCS", "HCLTECH", "TECHM", "WIPRO",
    "SAGILITY", "DLF", "SOBHA", "MOREALTY", "DIXON", "LICI", "HDFCLIFE", "SBIN", "HDFCBANK",
    "BANKBEES", "NIFTYBEES", "ITBEES", "HDFCSML250", "MIDCAPETF", "MODEFENCE",
    "FMCGIETF", "GROWWPOWER", "GOLDBEES", "SILVERBEES", "INFY", "ICICIBANK",
    "AXISBANK", "KOTAKBANK", "LT", "HINDUNILVR", "BHARTIARTL", "TMCV", "TMPV",
    "SBILIFE", "TATASTEEL", "ADANIENT", "ASIANPAINT", "MARUTI", "SUNPHARMA",
    "NTPC", "POWERGRID", "TITAN", "COALINDIA", "BAJAJFINSV", "BPCL", "ONGC",
    "JSWSTEEL", "HINDALCO", "GRASIM", "EICHERMOT", "JINDALSTEL", "HAL", "BEL",
    "ETERNAL", "TRENT", "MUTHOOTFIN", "RECLTD", "PFC", "BHEL", "RVNL", "IRFC",
    "MAZDOCK", "SUZLON"
]

# NIFTY 50 constituents — sourced from https://dhan.co/nifty-stocks-list/nifty-50/
NIFTY_50 = [
    "RELIANCE", "HDFCBANK", "BHARTIARTL", "ICICIBANK", "SBIN", "TCS", "BAJFINANCE", "LT",
    "HINDUNILVR", "SUNPHARMA", "INFY", "MARUTI", "ADANIPORTS", "ADANIENT", "AXISBANK", "TITAN",
    "M&M", "KOTAKBANK", "ITC", "ULTRACEMCO", "NTPC", "HCLTECH", "ONGC", "BAJAJFINSV", "JSWSTEEL",
    "BEL", "BAJAJ-AUTO", "ETERNAL", "NESTLEIND", "POWERGRID", "COALINDIA", "ASIANPAINT",
    "SHRIRAMFIN", "TATASTEEL", "HINDALCO", "GRASIM", "INDIGO", "EICHERMOT", "WIPRO", "SBILIFE",
    "JIOFIN", "TRENT", "TECHM", "APOLLOHOSP", "TMPV", "HDFCLIFE", "CIPLA", "MAXHEALTH",
    "TATACONSUM", "DRREDDY",
]

# NIFTY NEXT 50 constituents — sourced from https://dhan.co/nifty-stocks-list/nifty-next-50/
NIFTY_NEXT_50 = [
    "ADANIPOWER", "HAL", "DMART", "ADANIGREEN", "HINDZINC", "ADANIENSOL", "IOC", "DIVISLAB",
    "TVSMOTOR", "DLF", "TORNTPHARM", "SOLARINDS", "HYUNDAI", "PIDILITIND", "VBL", "TMCV",
    "CHOLAFIN", "CUMMINSIND", "TATACAP", "MOTHERSON", "ABB", "CGPOWER", "PFC", "BPCL",
    "BANKBARODA", "BRITANNIA", "UNIONBANK", "LTM", "SIEMENS", "BOSCHLTD", "MUTHOOTFIN", "ENRIN",
    "PNB", "TATAPOWER", "BAJAJHLDNG", "LODHA", "HDFCAMC", "IRFC", "CANBK", "ZYDUSLIFE", "GAIL",
    "GODREJCP", "AMBUJACEM", "INDHOTEL", "JINDALSTEL", "VEDL", "UNITDSPR", "MAZDOCK", "SHREECEM",
    "RECLTD",
]

# NIFTY MIDCAP 150 constituents — live from https://www.niftyindices.com/IndexConstituent/ind_niftymidcap150list.csv
NIFTY_MIDCAP_150 = [
    "360ONE", "3MINDIA", "ACC", "AIAENG", "APLAPOLLO", "AUBANK", "AWL", "ABBOTINDIA", "ATGL", "ABCAPITAL",
    "AJANTPHARM", "ALKEM", "ANTHEM", "APARINDS", "APOLLOTYRE", "ASHOKLEY", "ASTRAL", "AUROPHARMA", "AIIL", "BSE",
    "BAJAJHFL", "BALKRISIND", "BANKINDIA", "MAHABANK", "BERGEPAINT", "BDL", "BHARATFORG", "BHEL", "BHARTIHEXA", "GROWW",
    "BIOCON", "BLUESTARCO", "CRISIL", "COCHINSHIP", "COFORGE", "COLPAL", "CONCOR", "COROMANDEL", "DABUR", "DALBHARAT",
    "DIXON", "ENDURANCE", "ESCORTS", "EXIDEIND", "NYKAA", "FEDERALBNK", "FORTIS", "GVT&D", "GMRAIRPORT", "GICRE",
    "GLAXO", "GLENMARK", "MEDANTA", "GODFRYPHLP", "GODREJIND", "GODREJPROP", "FLUOROCHEM", "HDBFS", "HAVELLS", "HEROMOTOCO",
    "HEXT", "HINDPETRO", "POWERINDIA", "HONAUT", "HUDCO", "ICICIGI", "ICICIAMC", "ICICIPRULI", "IDFCFIRSTB", "ITCHOTELS",
    "INDIANB", "IRCTC", "IREDA", "INDUSTOWER", "INDUSINDBK", "NAUKRI", "IPCALAB", "JKCEMENT", "JSWENERGY", "JSWINFRA",
    "JSL", "JUBLFOOD", "KPRMILL", "KEI", "KPITTECH", "KALYANKJIL", "LTF", "LTTS", "LGEINDIA", "LICHSGFIN",
    "LAURUSLABS", "LENSKART", "LICI", "LINDEINDIA", "LLOYDSME", "LUPIN", "MRF", "M&MFIN", "MANKIND", "MARICO",
    "MFSL", "MOTILALOFS", "MPHASIS", "MCX", "NHPC", "NLCINDIA", "NMDC", "NTPCGREEN", "NATIONALUM", "NAM-INDIA",
    "OBEROIRLTY", "OIL", "PAYTM", "OFSS", "POLICYBZR", "PIIND", "PAGEIND", "PATANJALI", "PERSISTENT", "PETRONET",
    "PHOENIXLTD", "POLYCAB", "PREMIERENE", "PRESTIGE", "RADICO", "RVNL", "SBICARD", "SJVN", "SRF", "SCHAEFFLER",
    "SAIL", "SUNDARMFIN", "SUPREMEIND", "SUZLON", "SWIGGY", "TATACOMM", "TATAELXSI", "TATAINVEST", "NIACL", "THERMAX",
    "TORNTPOWER", "TIINDIA", "UNOMINDA", "UPL", "UBL", "VMM", "IDEA", "VOLTAS", "WAAREEENER", "YESBANK",
]

# NIFTY SMALLCAP 250 constituents — live from https://www.niftyindices.com/IndexConstituent/ind_niftysmallcap250list.csv
NIFTY_SMALLCAP_250 = [
    "ACMESOLAR", "AADHARHFC", "AARTIIND", "AAVAS", "ACE", "ACUTAAS", "ABFRL", "ABLBL", "ABREL", "ABSLAMC",
    "CPPLUS", "AEGISLOG", "AEGISVOPAK", "AFCONS", "AFFLE", "ABDL", "ARE&M", "AMBER", "ANANDRATHI", "ANANTRAJ",
    "ANGELONE", "ANURAS", "APTUS", "ASAHIINDIA", "ASTERDM", "ATHERENERG", "ATUL", "BEML", "BLS", "BALRAMCHIN",
    "BANDHANBNK", "BATAINDIA", "BAYERCROP", "BELRISE", "BIKAJI", "BSOFT", "BLUEDART", "BLUEJET", "BBTC", "FIRSTCRY",
    "BRIGADE", "MAPMYINDIA", "CCL", "CESC", "CIEINDIA", "CANFINHOME", "CANHLIFE", "CAPLIPOINT", "CGCL", "CARBORUNIV",
    "CARTRADE", "CASTROLIND", "CEATLTD", "CEMPRO", "CENTRALBK", "CDSL", "CHALET", "CHAMBLFERT", "CHENNPETRO", "CHOICEIN",
    "CHOLAHLDNG", "CUB", "CLEAN", "COHANCE", "CAMS", "CONCORDBIO", "CRAFTSMAN", "CREDITACC", "CROMPTON", "CYIENT",
    "DCMSHRIRAM", "DOMS", "DATAPATTNS", "DEEPAKFERT", "DEEPAKNTR", "DELHIVERY", "DEVYANI", "LALPATHLAB", "EIDPARRY", "EIHOTEL",
    "ELECON", "ELGIEQUIP", "EMAMILTD", "EMCURE", "EMMVEE", "ENGINERSIN", "ERIS", "FACT", "FINCABLES", "FSL",
    "FIVESTAR", "FORCEMOT", "GABRIEL", "GALLANTT", "GRSE", "GILLETTE", "GLAND", "GODIGIT", "GPIL", "GRANULES",
    "GRAPHITE", "GRAVITA", "GESHIP", "GMDCLTD", "HEG", "HBLENGINE", "HFCL", "HSCL", "HINDCOPPER", "HOMEFIRST",
    "HONASA", "IDBI", "IFCI", "IIFL", "IRB", "IRCON", "ITI", "INDGN", "INDIACEM", "INDIAMART",
    "IEX", "IOB", "IGL", "INOXWIND", "INTELLECT", "IGIL", "IKS", "JBMA", "JKTYRE", "JMFINANCIL",
    "JSWCEMENT", "JSWDULUX", "JAINREC", "JPPOWER", "J&KBANK", "JINDALSAW", "JUBLINGREA", "JUBLPHARMA", "JWL", "JYOTICNC",
    "KAJARIACER", "KPIL", "KARURVYSYA", "KAYNES", "KEC", "KFINTECH", "KIRLOSENG", "KIMS", "LTFOODS", "LATENTVIEW",
    "THELEELA", "LEMONTREE", "MMTC", "MGL", "MANAPPURAM", "MRPL", "MEESHO", "MINDACORP", "MSUMI", "NATCOPHARM",
    "NBCC", "NCC", "NSLNISP", "NH", "NAVA", "NAVINFLUOR", "NETWEB", "NEULANDLAB", "NEWGEN", "NIVABUPA",
    "NUVAMA", "NUVOCO", "OLAELEC", "OLECTRA", "ONESOURCE", "PCBL", "PGEL", "PNBHOUSING", "PTCIL", "PVRINOX",
    "PARADEEP", "PFIZER", "PWL", "PINELABS", "PIRAMALFIN", "PPLPHARMA", "POLYMED", "POONAWALLA", "PFOCUS", "RRKABEL",
    "RBLBANK", "RHIM", "RITES", "RAILTEL", "RAINBOW", "RKFORGE", "REDINGTON", "RPOWER", "SBFC", "SAGILITY",
    "SAILIFE", "SAMMAANCAP", "SAPPHIRE", "SARDAEN", "SAREGAMA", "SCHNEIDER", "SCI", "SHYAMMETL", "SIGNATURE", "SOBHA",
    "SONACOMS", "SONATSOFTW", "STARHEALTH", "SUMICHEM", "SUNTV", "SPLPETRO", "SWANCORP", "SYNGENE", "SYRMA", "TBOTEK",
    "TATACHEM", "TATATECH", "TTML", "TECHNOE", "TEGA", "TEJASNET", "TENNIND", "RAMCOCEM", "TIMKEN", "TITAGARH",
    "TARIL", "TRAVELFOOD", "TRIDENT", "TRITURBINE", "UCOBANK", "UTIAMC", "URBANCO", "USHAMART", "VTL", "VIJAYA",
    "WELCORP", "WELSPUNLIV", "WHIRLPOOL", "WOCKPHARMA", "ZFCVINDIA", "ZEEL", "ZENTEC", "ZENSARTECH", "ZYDUSWELL", "ECLERX",
]

# NIFTY 500 = NIFTY 50 + NIFTY NEXT 50 + NIFTY MIDCAP 150 + NIFTY SMALLCAP 250 (dedup) —
# matches NSE's own construction of the index; live-verified counts (50+50+150+250 with
# overlap dedup) against https://www.niftyindices.com/IndexConstituent/ind_nifty500list.csv
NIFTY_500 = list(set(NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP_150 + NIFTY_SMALLCAP_250))

# Major Indices for Scan Universe — sourced from https://dhan.co/nifty-stocks-list/
NIFTY_BANK = [
    "HDFCBANK", "ICICIBANK", "SBIN", "AXISBANK", "KOTAKBANK", "BANKBARODA", "UNIONBANK", "PNB",
    "CANBK", "FEDERALBNK", "AUBANK", "INDUSINDBK", "YESBANK", "IDFCFIRSTB",
]

NIFTY_IT = [
    "TCS", "INFY", "HCLTECH", "WIPRO", "TECHM", "LTM", "OFSS", "PERSISTENT", "COFORGE", "MPHASIS",
]

# NIFTY FINANCIAL SERVICES (a.k.a. FinNifty) — https://dhan.co/nifty-stocks-list/nifty-fin-services/
NIFTY_FINANCIAL = [
    "HDFCBANK", "ICICIBANK", "SBIN", "BAJFINANCE", "AXISBANK", "KOTAKBANK", "BAJAJFINSV",
    "SHRIRAMFIN", "SBILIFE", "JIOFIN", "CHOLAFIN", "BSE", "PFC", "HDFCLIFE", "MUTHOOTFIN",
    "RECLTD", "ICICIGI", "SBICARD", "MFSL", "LICHSGFIN",
]

NIFTY_AUTO = [
    "MARUTI", "M&M", "BAJAJ-AUTO", "EICHERMOT", "TVSMOTOR", "MOTHERSON", "TMPV", "BOSCHLTD",
    "BHARATFORG", "HEROMOTOCO", "ASHOKLEY", "UNOMINDA", "TIINDIA", "SONACOMS", "EXIDEIND",
]

NIFTY_FMCG = [
    "HINDUNILVR", "ITC", "NESTLEIND", "VBL", "BRITANNIA", "MARICO", "GODREJCP", "TATACONSUM",
    "UNITDSPR", "DABUR", "COLPAL", "RADICO", "PATANJALI", "UBL", "EMAMILTD",
]

NIFTY_PHARMA = [
    "SUNPHARMA", "DIVISLAB", "TORNTPHARM", "CIPLA", "LUPIN", "ZYDUSLIFE", "MANKIND", "DRREDDY",
    "AUROPHARMA", "LAURUSLABS", "ALKEM", "BIOCON", "GLENMARK", "ABBOTINDIA", "IPCALAB",
    "AJANTPHARM", "GLAND", "JBCHEPHARM", "WOCKPHARMA", "PPLPHARMA",
]

NIFTY_METAL = [
    "ADANIENT", "JSWSTEEL", "TATASTEEL", "HINDZINC", "HINDALCO", "JINDALSTEL", "VEDL",
    "LLOYDSME", "NMDC", "SAIL", "NATIONALUM", "JSL", "APLAPOLLO", "HINDCOPPER", "WELCORP",
]

NIFTY_REALTY = [
    "DLF", "LODHA", "PHOENIXLTD", "PRESTIGE", "OBEROIRLTY", "GODREJPROP", "ANANTRAJ", "BRIGADE",
    "SOBHA", "ABREL",
]

NIFTY_ENERGY = [
    "RELIANCE", "ADANIPOWER", "NTPC", "ONGC", "POWERGRID", "COALINDIA", "ADANIGREEN",
    "ADANIENSOL", "IOC", "ABB", "BHEL", "CGPOWER", "POWERINDIA", "BPCL", "SIEMENS", "ENRIN",
    "TATAPOWER", "GVT&D", "GAIL", "JSWENERGY", "HINDPETRO", "NTPCGREEN", "ATGL", "NHPC",
    "SUZLON", "TORNTPOWER", "OIL", "THERMAX", "AEGISLOG", "NLCINDIA", "PETRONET", "SJVN", "IGL",
    "CESC", "CASTROLIND", "NAVA", "INOXWIND", "JPPOWER", "MGL", "RPOWER",
]

from app.market_pulse.high_vol_etf_tickers import HIGH_VOL_ETF
from app.market_pulse.nifty_index_constituents import (
    NIFTY_CEMENT,
    NIFTY_CHEMICALS,
    NIFTY_CONSUMER_DURABLES,
    NIFTY_FINANCIAL_SERVICES_EX_BANK,
    NIFTY_HEALTHCARE,
)

NIFTY_MIDCAP = NIFTY_MIDCAP_150

# ---------------------------------------------------------------------------
# US markets — full index lists via us_index_constituents (lazy-loaded)
# ---------------------------------------------------------------------------

from app.market_pulse.us_index_constituents import (  # noqa: E402
    DOW_30_STATIC as DOW_30,
    US_INDEX_ETFS,
    get_us_index_options,
)

INDEX_OPTIONS = {
    "Default Groww Tickers": DEFAULT_GROWW_TICKERS,
    "High Vol ETF": HIGH_VOL_ETF,
    "NIFTY 50": NIFTY_50,
    "NIFTY NEXT 50": NIFTY_NEXT_50,
    "NIFTY BANK": NIFTY_BANK,
    "NIFTY IT": NIFTY_IT,
    "NIFTY FINANCIAL SERVICES": NIFTY_FINANCIAL,
    "NIFTY AUTO": NIFTY_AUTO,
    "NIFTY FMCG": NIFTY_FMCG,
    "NIFTY PHARMA": NIFTY_PHARMA,
    "NIFTY METAL": NIFTY_METAL,
    "NIFTY REALTY": NIFTY_REALTY,
    "NIFTY ENERGY": NIFTY_ENERGY,
    "NIFTY CEMENT": NIFTY_CEMENT,
    "NIFTY CHEMICALS": NIFTY_CHEMICALS,
    "NIFTY CONSUMER DURABLES": NIFTY_CONSUMER_DURABLES,
    "NIFTY HEALTHCARE": NIFTY_HEALTHCARE,
    "NIFTY FINANCIAL SERVICES EX-BANK": NIFTY_FINANCIAL_SERVICES_EX_BANK,
    "NIFTY MIDCAP 150": NIFTY_MIDCAP,
    "NIFTY SMALLCAP 250": NIFTY_SMALLCAP_250,
    "NIFTY 500": NIFTY_500
}

# Market labels (shared across tabs)
GROWW_MARKET = "Groww (India Stocks)"
US_MARKET = "US Stocks (Yahoo)"
CRYPTO_MARKET = "CoinDCX Futures"
MARKET_OPTIONS = [GROWW_MARKET, US_MARKET, CRYPTO_MARKET]


def is_crypto_market(market: str) -> bool:
    return "CoinDCX" in (market or "")


def is_us_market(market: str) -> bool:
    m = (market or "").strip()
    return m == US_MARKET or "US Stocks" in m


def is_india_market(market: str) -> bool:
    return not is_crypto_market(market) and not is_us_market(market)


def market_currency(market: str) -> str:
    if is_india_market(market):
        return "₹"
    return "$"


def get_index_options_for_market(market: str) -> dict[str, list[str]]:
    if is_us_market(market):
        return get_us_index_options()
    return INDEX_OPTIONS


COINDCX_USDT_TICKERS = [
    "B-BTCUSDT", "B-ETHUSDT", "B-SOLUSDT", "B-XRPUSDT", "B-DOGEUSDT",
    "B-ADAUSDT", "B-AVAXUSDT", "B-LINKUSDT", "B-DOTUSDT", "B-NEARUSDT",
    "B-LTCUSDT", "B-SHIBUSDT", "B-PEPEUSDT", "B-WIFUSDT", "B-BONKUSDT",
    "B-JUPUSDT", "B-ONDOUSDT", "B-OMUSDT", "B-FLOKIUSDT", "B-SUIUSDT",
    "B-RENDERUSDT", "B-TAOUSDT", "B-FETUSDT", "B-ARUSDT", "B-TIAUSDT",
    "B-SEIUSDT", "B-STRKUSDT", "B-OPUSDT", "B-ARBUSDT", "B-LDOUSDT",
    "B-UNIUSDT", "B-ICPUSDT", "B-ALGOUSDT", "B-VETUSDT", "B-XLMUSDT",
    "B-ATOMUSDT", "B-GRTUSDT", "B-IMXUSDT", "B-RUNEUSDT", "B-THETAUSDT",
    "B-INJUSDT", "B-STXUSDT", "B-AAVEUSDT", "B-MKRUSDT", "B-GMTUSDT",
    "B-GALAUSDT", "B-ZILUSDT", "B-KAVAUSDT", "B-JASMYUSDT", "B-WLDUSDT",
    "B-CRVUSDT", "B-1INCHUSDT", "B-MINAUSDT", "B-ENJUSDT", "B-FLOWUSDT",
    "B-MANAUSDT", "B-SANDUSDT", "B-AXSUSDT", "B-DYDXUSDT", "B-BATUSDT",
    "B-WOOUSDT", "B-KSMUSDT", "B-QTUMUSDT", "B-ZRXUSDT", "B-ONEUSDT",
    "B-HOTUSDT", "B-CELOUSDT", "B-RVNUSDT", "B-ROSEUSDT", "B-IOTXUSDT",
    "B-EGLDUSDT", "B-RSRUSDT", "B-STGUSDT", "B-SPELLUSDT", "B-LUNA2USDT",
    "B-SFPUSDT", "B-COMPUSDT", "B-YFIUSDT", "B-SNXUSDT", "B-POLUSDT",
    "B-SAGAUSDT", "B-SPXUSDT", "B-BASEDUSDT", "B-SAPIENUSDT", "B-FHEUSDT", "B-ATAUSDT",
    "B-MERLUSDT", "B-STABLEUSDT", "B-2ZUSDT", "B-FIGHTUSDT", "B-GTCUSDT",
    "B-REZUSDT", "B-SYSUSDT", "B-PRLUSDT", "B-MITOUSDT", "B-HUSDT", "B-EIGENUSDT",
    "B-NFPUSDT", "B-BERAUSDT", "B-CHILLGUYUSDT", "B-CATIUSDT", "B-OPNUSDT", "B-CETUSUSDT", "B-WUSDT",
    "B-PYTHUSDT", "B-EULUSDT", "B-AIGENSYNUSDT", "B-MAVIAUSDT", "B-SWARMSUSDT", "B-KMNOUSDT", "B-LUMIAUSDT",
    "B-ATHUSDT", "B-ACEUSDT", "B-MEWUSDT", "B-XAGUSDT", "B-AKTUSDT", "B-XPLUSDT", "B-WALUSDT",
    "B-DOLOUSDT", "B-ACTUSDT", "B-FARTCOINUSDT", "B-INITUSDT", "B-BBUSDT",
    "B-PLUMEUSDT", "B-1000000MOGUSDT", "B-PHAUSDT", "B-BANANAS31USDT", "B-MOVRUSDT", "B-FOGOUSDT",
    "B-IOUSDT", "B-ALTUSDT", "B-EDUUSDT", "B-MOCAUSDT", "B-SIGNUSDT", "B-0GUSDT",
    "B-ZKUSDT", "B-AGLDUSDT", "B-SOLVUSDT", "B-CUSDT", "B-MBOXUSDT", "B-BLURUSDT",
    "B-MANTAUSDT", "B-ZROUSDT", "B-XAIUSDT", "B-LISTAUSDT", "B-TURTLEUSDT", "B-EDGEUSDT",
    "B-TREEUSDT", "B-IOTAUSDT", "B-BRETTUSDT", "B-SCRTUSDT", "B-DYMUSDT", "B-MANTRAUSDT", "B-COTIUSDT",
    "B-EPICUSDT", "B-FIDAUSDT", "B-ETHFIUSDT", "B-NXPCUSDT", "B-CARVUSDT", "B-SCRUSDT", "B-YGGUSDT",
    "B-SHELLUSDT", "B-RPLUSDT", "B-BMTUSDT", "B-JOEUSDT", "B-USUALUSDT", "B-EDENUSDT", "B-C98USDT", "B-HEMIUSDT",
    "B-HFTUSDT", "B-CFXUSDT", "B-TNSRUSDT", "B-HAEDALUSDT", "B-PIXELUSDT", "B-MOODENGUSDT", "B-LQTYUSDT",
    "B-VANRYUSDT", "B-SKLUSDT", "B-ONGUSDT", "B-SXTUSDT", "B-MEMEUSDT", "B-MMTUSDT", "B-TRUMPUSDT",
    "B-DIAUSDT", "B-IDUSDT", "B-BICOUSDT", "B-ENSUSDT", "B-MORPHOUSDT", "B-TONUSDT", "B-BIGTIMEUSDT",
    "B-IOSTUSDT", "B-LAUSDT", "B-DRIFTUSDT", "B-MAVUSDT", "B-ICNTUSDT", "B-DEEPUSDT",
    "B-ORDIUSDT", "B-GOATUSDT", "B-PORTALUSDT", "B-AVAUSDT", "B-IPUSDT",
    "B-MAGICUSDT", "B-AUSDT", "B-ARKMUSDT", "B-CHRUSDT", "B-FLUIDUSDT", "B-CFGUSDT", "B-NILUSDT", "B-ZKCUSDT",
    "B-SSVUSDT", "B-FRAXUSDT", "B-MIRAUSDT", "B-BREVUSDT", "B-AVNTUSDT", "B-ILVUSDT",
    "B-MASKUSDT", "B-SOMIUSDT", "B-BIOUSDT", "B-THEUSDT", "B-NEWTUSDT", "B-BANDUSDT",
    "B-WCTUSDT", "B-SYNUSDT", "B-APEUSDT", "B-PEOPLEUSDT", "B-ERAUSDT", "B-GRASSUSDT",
    "B-ZETAUSDT", "B-API3USDT", "B-FLUXUSDT", "B-SONICUSDT", "B-1000SATSUSDT",
    "B-METISUSDT", "B-KASUSDT", "B-LINEAUSDT", "B-YBUSDT", "B-HIGHUSDT", "B-HMSTRUSDT",
    "B-WETUSDT", "B-POPCATUSDT", "B-HEIUSDT", "B-TLMUSDT", "B-ONTUSDT",
    "B-NOTUSDT", "B-SUSHIUSDT", "B-MOVEUSDT", "B-RLCUSDT", "B-SUSDT", "B-USTCUSDT", "B-BOMEUSDT",
    "B-STOUSDT", "B-KOMAUSDT", "B-CYBERUSDT", "B-1000CATUSDT", "B-BROCCOLI714USDT", "B-GUSDT", "B-RAREUSDT",
    "B-RAVEUSDT", "B-KATUSDT", "B-MEGAUSDT", "B-METUSDT", "B-RONINUSDT",
    "B-RESOLVUSDT", "B-SKRUSDT", "B-PROVEUSDT", "B-ETHWUSDT", "B-ZENUSDT",
    "B-SYRUPUSDT", "B-TOWNSUSDT", "B-AXLUSDT", "B-ALICEUSDT", "B-LSKUSDT", "B-TACUSDT", "B-BSVUSDT", "B-MEUSDT", "B-ALPINEUSDT", "B-VELODROMEUSDT",
    "B-AVAAIUSDT", "B-CTSIUSDT", "B-ANIMEUSDT", "B-VTHOUSDT", "B-ROBOUSDT",
    "B-SAFEUSDT", "B-ARKUSDT", "B-SOPHUSDT", "B-ICXUSDT", "B-NEOUSDT", "B-SUPERUSDT", "B-COWUSDT", "B-MONUSDT", "B-SENTUSDT", "B-AEROUSDT", "B-GASUSDT", "B-ACUUSDT",
    "B-PUMPUSDT", "B-SAHARAUSDT", "B-BANANAUSDT", "B-HIVEUSDT", "B-VVVUSDT", "B-OGNUSDT",
    "B-LPTUSDT", "B-FUSDT", "B-MUBARAKUSDT", "B-NOMUSDT", "B-TAIKOUSDT",
    "B-GENIUSUSDT", "B-MELANIAUSDT", "B-PNUTUSDT", "B-PUNDIXUSDT", "B-UMAUSDT",
    "B-DOGSUSDT", "B-ALLOUSDT", "B-REDUSDT", "B-LAYERUSDT", "B-COOKIEUSDT", "B-1MBABYDOGEUSDT",
    "B-TUSDT", "B-GIGGLEUSDT", "B-PIPPINUSDT", "B-XMRUSDT", "B-BELUSDT", "B-WLFIUSDT",
    "B-KITEUSDT", "B-WAXPUSDT", "B-FORMUSDT", "B-XTZUSDT", "B-CHIPUSDT", "B-LITUSDT", "B-XVSUSDT", "B-PENGUUSDT",
    "B-BARDUSDT", "B-ACHUSDT", "B-ZKPUSDT", "B-TWTUSDT", "B-TUTUSDT", "B-HOLOUSDT", "B-BNTUSDT",
    "B-BANKUSDT", "B-KAITOUSDT", "B-KAIAUSDT", "B-SANTOSUSDT", "B-BIRBUSDT",
    "B-HUMAUSDT", "B-HYPERUSDT", "B-GRIFFAINUSDT", "B-MTLUSDT", "B-PHBUSDT", "B-GLMUSDT", "B-VANAUSDT",
    "B-AIXBTUSDT", "B-CLANKERUSDT", "B-HBARUSDT", "B-CAKEUSDT", "B-XANUSDT"
]


def get_coindcx_ticker_list():
    return [{"symbol": t, "display": t.replace("B-", "").replace("USDT", "-USDT")} for t in COINDCX_USDT_TICKERS]
