import {
  LayoutDashboard,
  Search,
  LineChart,
  Wallet,
  Settings,
  TrendingUp,
  BookOpen,
  Activity,
  BarChart3,
  Layers,
  Landmark,
  Compass,
  Beaker,
  CalendarRange,
  Bell,
  Eye,
  ArrowUp,
  Calculator,
  Target,
  Clapperboard,
  Bot,
  Crosshair,
  Radar,
  ListTodo,
  Trophy,
  MessageSquare,
  Sparkles,
  GitBranch,
  Medal,
  Building2,
  Flame,
  type LucideIcon,
} from 'lucide-react'

export type NavChild = { to: string; label: string }
export type NavEntry = {
  to: string
  label: string
  shortLabel: string
  icon: LucideIcon
  children?: NavChild[]
}

/** Primary sidebar navigation — single source of truth for layout + global search. */
export const appNav: NavEntry[] = [
  { to: '/trading-agent', label: 'Trading Agent (TA)', shortLabel: 'TA', icon: MessageSquare },
  { to: '/investing-agent', label: 'Investing Agent (FA)', shortLabel: 'FA', icon: Bot },
  {
    to: '/workflow',
    label: 'Workflow',
    shortLabel: 'Flow',
    icon: GitBranch,
    children: [
      { to: '/workflow/india', label: 'India (F&O / Intraday)' },
      { to: '/workflow/us', label: 'US (Swing / Pairs)' },
      { to: '/workflow/crypto', label: 'Crypto (Scalp / Intraday)' },
      { to: '/workflow/commodities', label: 'Commodities (Gold / Oil)' },
    ],
  },
  {
    to: '/best-strategies',
    label: 'Best Strategies',
    shortLabel: 'Best',
    icon: Medal,
    children: [
      { to: '/best-strategies/india', label: 'India (Equities & F&O)' },
      { to: '/best-strategies/us', label: 'US Equities' },
      { to: '/best-strategies/crypto', label: 'Crypto' },
      { to: '/best-strategies/commodities', label: 'Commodities' },
    ],
  },
  {
    to: '/institutional-accuracy',
    label: 'Institutional Accuracy',
    shortLabel: 'Inst',
    icon: Building2,
    children: [
      { to: '/institutional-accuracy/india', label: 'India' },
      { to: '/institutional-accuracy/us', label: 'US' },
      { to: '/institutional-accuracy/crypto', label: 'Crypto' },
      { to: '/institutional-accuracy/commodities', label: 'Commodities' },
    ],
  },
  { to: '/dashboard', label: 'Dashboard', shortLabel: 'Home', icon: LayoutDashboard },
  { to: '/auto-trade', label: 'Auto Trade', shortLabel: 'Auto', icon: Radar },
  {
    to: '/command-center',
    label: 'Command Center',
    shortLabel: 'Command',
    icon: Compass,
    children: [
      { to: '/command-center', label: 'Tools & scanners' },
      { to: '/command-center?tab=all_strategies', label: 'All Strategies Explained' },
      { to: '/command-center?tab=playbook', label: 'Trading Playbook' },
      { to: '/command-center?tab=mega_analyser', label: 'Mega Analyser' },
      { to: '/command-center?tab=buy_sell', label: 'Buy or Sell' },
      { to: '/command-center?tab=advance_decline_graph', label: 'Advance Decline' },
      { to: '/command-center?tab=comparative_strength', label: 'Comparative Strength' },
      { to: '/command-center?tab=oil_dollar_bond', label: 'Oil · Dollar · Bond' },
      { to: '/command-center?tab=option_chain', label: 'Option Chain' },
      { to: '/strategy-lab', label: 'Strategy Lab Encyclopedia' },
    ],
  },
  { to: '/strategies', label: 'Strategies', shortLabel: 'Rules', icon: BookOpen },
  { to: '/market-pulse', label: 'Market Pulse', shortLabel: 'Pulse', icon: Activity },
  { to: '/etf-ta-in', label: 'ETF TA IN', shortLabel: 'ETF', icon: Landmark },
  { to: '/etf-28-sma', label: 'ETF 28 SMA', shortLabel: '28 SMA', icon: TrendingUp },
  { to: '/etf-top-down', label: 'ETF Top Down', shortLabel: 'Top Down', icon: ArrowUp },
  { to: '/trading-hubs', label: 'Trading Hubs', shortLabel: 'Hubs', icon: Layers },
  {
    to: '/trade-candidate',
    label: 'Trade Candidate',
    shortLabel: 'Candidate',
    icon: Target,
    children: [
      { to: '/trade-candidate/configure', label: 'Configure' },
      { to: '/trade-candidate/signals-crypto', label: 'Live Signals · Crypto' },
      { to: '/trade-candidate/signals-india', label: 'Live Signals · India' },
      { to: '/trade-candidate/signals-us', label: 'Live Signals · US' },
      { to: '/trade-candidate/signals-commodity', label: 'Live Signals · Commodities' },
      { to: '/trade-candidate/setups', label: 'Saved Setups' },
      { to: '/trade-candidate/history-crypto', label: 'Trigger History · Crypto' },
      { to: '/trade-candidate/history-india', label: 'Trigger History · India' },
      { to: '/trade-candidate/history-us', label: 'Trigger History · US' },
      { to: '/trade-candidate/history-commodity', label: 'Trigger History · Commodities' },
    ],
  },
  { to: '/options', label: 'Options', shortLabel: 'Options', icon: Calculator },
  {
    to: '/pro-trade',
    label: 'Pro Trade',
    shortLabel: 'Pro',
    icon: Crosshair,
    children: [
      { to: '/pro-trade/volume-profile-ce', label: 'Volume Profile CE' },
      { to: '/pro-trade/volume-profile-poc', label: 'Volume Profile POC' },
      { to: '/pro-trade/pa-volume-profile', label: 'PA - Volume Profile' },
      { to: '/pro-trade/pa-vp-smc', label: 'PA-VP-SMC' },
      { to: '/pro-trade/volume-spread-next-candle', label: 'Volume Spread - Next Candle' },
      { to: '/pro-trade/elliott-wave', label: 'Elliott Wave' },
      { to: '/pro-trade/fibonacci-pro', label: 'Fibonacci Pro' },
      { to: '/pro-trade/bb-mean-reversion', label: 'BB Mean Reversion' },
      { to: '/pro-trade/traffic-light-indicator', label: 'Traffic Light Indicator' },
      { to: '/pro-trade/buy-low-sell-high', label: 'Buy Low Sell High' },
      { to: '/pro-trade/rlb-breakout', label: 'RLB - Breakout' },
      { to: '/pro-trade/3-in-1-trade-system', label: '3-in-1 Trade System' },
      { to: '/pro-trade/simple-effective', label: 'Simple Effective' },
      { to: '/pro-trade/bb-rsi-vol', label: 'BB-RSI-VOL' },
      { to: '/pro-trade/ema9-cross', label: '9 EMA Cross' },
      { to: '/pro-trade/ema5-cross', label: '5 EMA Cross' },
      { to: '/pro-trade/ema5-9-cross', label: '5/9 EMA Cross' },
      { to: '/trading-hubs?hub=swing&section=support_resistance', label: 'Support & Resistance' },
      { to: '/pro-trade/btst', label: 'Buy Today Sell Tomorrow' },
      { to: '/pro-trade/ticker-chart', label: 'Ticker Chart' },
    ],
  },
  {
    to: '/prediction',
    label: 'Prediction',
    shortLabel: 'Predict',
    icon: Sparkles,
    children: [
      { to: '/prediction/pattern-analogue', label: 'Pattern Analogue' },
      { to: '/prediction/astro-finance', label: 'Astro Finance' },
      { to: '/prediction/falling-knife', label: 'Falling Knife' },
      { to: '/options?section=market_prediction', label: 'Market Prediction' },
      { to: '/options?section=call_put_writing', label: 'Call Put Writing' },
    ],
  },
  { to: '/technical-analysis', label: 'Technical Analysis', shortLabel: 'TA', icon: BarChart3 },
  { to: '/strategy-lab', label: 'Strategy Lab', shortLabel: 'Lab', icon: Beaker },
  { to: '/seasonality', label: 'Seasonality', shortLabel: 'Season', icon: CalendarRange },
  { to: '/youtube-analysis', label: 'Youtube Analysis', shortLabel: 'YT', icon: Clapperboard },
  { to: '/alerts', label: 'Alerts', shortLabel: 'Alerts', icon: Bell },
  { to: '/watchlist', label: 'Watchlist', shortLabel: 'Watch', icon: Eye },
  { to: '/todos', label: 'Todos', shortLabel: 'Todos', icon: ListTodo },
  { to: '/best-mf', label: 'Best MF', shortLabel: 'Best MF', icon: Trophy },
  { to: '/mf-fire', label: 'MF FIRE', shortLabel: 'FIRE', icon: Flame },
  { to: '/scanner', label: 'Scanner', shortLabel: 'Scan', icon: Search },
  { to: '/backtester', label: 'Backtester', shortLabel: 'Test', icon: LineChart },
  { to: '/paper', label: 'Paper Trading', shortLabel: 'Paper', icon: Wallet },
  { to: '/settings', label: 'Manage', shortLabel: 'Settings', icon: Settings },
]
